"""empty message

Revision ID: 6305d80d8018
Revises: 6c2e4b5e7dbe
Create Date: 2024-05-12 12:48:55.190424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6305d80d8018'
down_revision = '6c2e4b5e7dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=5), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
